### ISSUE TITLE
[META] Integration Testing

### ISSUE THREAD

**Issue by DanHatesNumbers** [simplybusiness/Kiln#43]
Parts of the Data-collector project are very hard to test at a unit test level (notably the Kafka integration) because the KafkaProducer automatically tries to connect to the cluster on creation.

Additional, there is currently no testing of how this component interacts with a real Kafka cluster. When Kiln grows to include more components, the need for integration testing will only grow.

Integration testing between the data-collector, the data-forwarder and a real Kafka cluster should be setup.

**Comment by DanHatesNumbers** [comment]
My current ideas for how to implement this are to use LocalStack to setup an API Gateway, Lambda using a release build of the data collector and CloudWatch for logs, all emulating what the Serverless deploy would create. The lambda could be configured to point at a locally running dockerised Kafka cluster (https://hub.docker.com/r/wurstmeister/kafka/) and then we could either test it with an HTTP client or the data forwarder binary and

**Comment by DanHatesNumbers** [comment]
Notes I've found on setting up LocalStack with Lambda and API Gateway https://gist.github.com/crypticmind/c75db15fd774fe8f53282c3ccbe3d7ad

**Comment by DanHatesNumbers** [comment]
Because the Rusoto crate for AWS supports custom regions, that could be used to interact with a localstack instance. There is a rust crate called Shiplift we can use to start the container for service connectors.

**Comment by DanHatesNumbers** [comment]
There is a crate for running Mock HTTP services that could be used to mock out the Slack API for instance https://docs.rs/mockito/0.21.0/mockito/

**Comment by DanHatesNumbers** [comment]
There's a Serverless framework plugin to integrate with LocalStack https://github.com/localstack/serverless-localstack

**Comment by DanHatesNumbers** [comment]
The Kafka create used by Kiln also does dockerised integration testing: https://github.com/spicavigo/kafka-rust/blob/master/tests/run-all-tests

**Comment by DanHatesNumbers** [comment]
Current thoughts on how this could be achieved:

- Docker-compose to bring up a Kiln deployment
- Using https://hub.docker.com/r/wurstmeister/kafka/ for Kafka + ZooKeeper
- Data-collector component validates hostnames for KAFKA_BOOTSTRAP_TLS config, but docker-compose provides hostnames that will resolve to running containers
- Data-collector will only connect over TLS, so we need to create a PKI, add the CA to the trust store for the Data-collector container (but only during testing) and get the generated certificates into the Kafka containers.

**Comment by ed-woodfall** [comment]
I've had a little success with https://hub.docker.com/r/wurstmeister/kafka/ it requires some ENV settings in the docker-compose.yml and to copy the certs and stores in the Kafka Dockerfile. Still working on it as it is still very rough.
```
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.18 
      KAFKA_SSL_TLS_VERSION: tLSv1.2
      KAFKA_SSL_SECURE_RANDOM_IMPLEMENTATION: NativePRNG
      KAFKA_SSL_CIPHER_SUITES: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
      KAFKA_SSL_KEYSTORE_LOCATION: /server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: password
      KAFKA_SSL_KEY_PASSWORD: password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: password
```
